### ISSUE TITLE
Renaming of Resources Dropbox for AAT

### ISSUE THREAD

**Issue by damienh** [ucfalmouth/LearningspaceTheme#48]
Hi Aaron,

as we spoke on Friday, Susan Lamb has got back to me and stated that Assessment Information would be appropriate for the renaming of Results Release. @aaronmarruk let me know if there is anything you want adding to the change log so we can get these changes done for this week. Ideally would be great to have the changes done by Wednesday as AAT have a schedule.

**Comment by Asampson** [comment]
This has been done.
